title: Troy Stories
description: 'Sharing stories from the people of Troy, NY.'

author:
  name: 'Jesse Gardner'
  email: jesse@plasticmind.com
  # Avatar image optional (under your/site/user/themes/masonry/images/avatar.png)
  image: avatar.jpg
  # Optional
  link: 'https://twitter.com/troy_stories'
  # Optional
  location: Troy, NY
  # Optional
  bio: 'I’ve been designing and developing for the web for twenty years.'

metadata:
  generator: ""